### ISSUE TITLE
Widget hostgroup : Extrème lenteur des requètes

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-hostgroup-monitoring#1]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 4602, https://forge.centreon.com/issues/4602
Original Date: 2013-07-07

---

centreon-widget-hostgroup-monitoring-1.1.1
Dans un environnement de 700 hosts, 1400 services et 64 hostgroup,la requête du widget des hostgroups mets 35 sec pour afficher 15 hosts.
Optimisation de la requète à prévoir car la requête met le serveur mysql à plat dans une archi distribuée rendant impossible l'utilisation même de centreon (10 mn pour afficher la vue monitoring).
Obligation de supprimer les vues en base pour pouvoir travailler normalement.

**Comment by Tpo76** [comment]
OK
