### ISSUE TITLE
Widjets  Hostgroup Monitoring 100% mysql

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-hostgroup-monitoring#2]
---

Author Name: **Maxx Max** (Maxx Max)
Original Redmine Issue: 4503, https://forge.centreon.com/issues/4503
Original Date: 2013-05-30

---

Bonjour,
Lorsque j'ajoute le widjet Hostgroup Monitoring à une vue personalisé centreon, cellui-ci plante le serveur mysql (100% CPU) Version du widjet Hostgroup Monitoring = 1.1.1

Le widjet lance cette requette pour chaque HostGroup : 

SELECT DISTINCT h.host_id, ss.current_state as state, s.service_id,h.display_name as name, s.service_object_id, s.display_name as description, hhg.hostgroup_id FROM nagios_hostgroup_members hhg, nagios_hosts h, nagios_hostgroups hg, nagios_hoststatus hs, nagios_objects o, nagios_services s, nagios_servicestatus ss WHERE h.host_object_id = hhg.host_object_id
  AND hhg.hostgroup_id = hg.hostgroup_id
   AND hg.hostgroup_object_id = o.object_id
  AND hhg.host_object_id = s.host_object_id
 AND s.service_object_id = ss.service_object_id
  AND s.host_object_id = h.host_object_id
  AND o.name1 = 'XXXXXXXXXXX'  ORDER BY h.display_name;
XXXX=correspond au Hostgroup

Est-il possible d'améliorer la requette mysql ou peut être que ma configuration mysql ne va pas !! 

Mon my.cnf : 

symbolic-links=0
innodb_file_per_table=1
skip-external-locking
max_allowed_packet = 4M
table_open_cache = 256
table_cache = 512
sort_buffer_size = 1M
read_buffer_size = 1M
join_buffer_size = 6M
read_rnd_buffer_size = 4M
myisam_sort_buffer_size = 64M
key_buffer_size = 256M
thread_cache_size = 17
query_cache_size = 128M
max_connections=200
interactive_timeout=10
wait_timeout=20
connect_timeout=20
thread_concurrency = 2

Ma configuration : Red Hat
nagios-core : 3.4.4
NdoUtil :  1.4b9-merethis
centreon : 2.4.0
mysql-serveur : Ver 14.14 Distrib 5.1.47

Nombre d'hôte : 670
Nom de service : 1900

Merci d'avance pour votre avis ou votre aide.

**Comment by Tpo76** [comment]
OK
