### ISSUE TITLE
Bug avec la modification ou suppression des hostgroups

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-hostgroup-monitoring#3]
---

Author Name: **daniel muro** (daniel muro)
Original Redmine Issue: 6271, https://forge.centreon.com/issues/6271
Original Date: 2015-03-30
Original Assignee: remi werquin

---

Bonjour,

Je viens d'installer et de mettre à jour un CES 3.1 chez un client, tout fonctionne sauf la mise à jour (edition ou suppression) des hostgroups.
En effet, lors d'une modification, par exemple une suppresion celui-ci reste toujours dans la liste des hostgroups (je peux le voir via le widget hostgroups dans le custom view).

Après plusieurs recherches je suis tombé sur un post similaire, ce qui m'a permi de voir que la liste des hostgroups n'étaient pas correctements mis à jour dans la table hostgroups de la bdd centreon_storage (je fais donc le ménage à la main via des requetes SQL).

Voici le lien en question:
http://forum.centreon.com/showthread.php/16472-Hostgroup-non-supprim%C3%A9-dans-la-bdd?p=81294

Version de centreon broker: 2.8.1
version de centreon ui: 2.5.4
Version de centreon engine 1.4.11

Pouvez-vous m'aider s'il vous plait à corriger ce problème ? nous avons d'autres clients à migrer que je ne peux pour le moment pas faire tant que ce problème persiste.

Merci par avance pour votre aide.

Cordialement,

Daniel.

**Comment by Tpo76** [comment]
OK
